### ISSUE TITLE
Install Flatpaks in Installer

### ISSUE THREAD

**Issue by lleyton** [tau-OS/isos#1]
Currently we ship the preinstalled apps within the base OSTree image. Moving to preinstalled Flatpaks would be ideal, as they are sandboxed, allow users to remove them, and keep the base image lean.

**Comment by korewaChino** [comment]
Currently, Fedora's OSTree builds actually do this. You have get an extra Lorax template and specify packages to add.

You can also check out Ultramarine's pungi compose files on how it works.

**Comment by nothingneko** [comment]
Which template?

**Comment by korewaChino** [comment]
> Which template?

https://github.com/Ultramarine-Linux/lorax-templates/blob/main/ostree-based-installer/lorax-embed-flatpaks.tmpl

**Comment by nothingneko** [comment]
Reopening this, the ISO fails to install flatpaks due to dependency issues and a lack of network connection, Anaconda considers this a fatal error.

**Comment by lleyton** [comment]
> dependency issues
What dependency issues? Logs?

More information is required before we can debug.

**Comment by nothingneko** [comment]
I'll attempt another install tonight for logs

**Comment by lleyton** [comment]
Updates?

**Comment by nothingneko** [comment]
Sorry, swamped, will get to it this week

**Comment by nothingneko** [comment]
Seems to be an isolated incident/fixed self. I can't recreate it
